### ISSUE TITLE
mapping import fails silently when .csv has wrong header

### ISSUE THREAD

**Issue by TravisWalterLBNL** [LBNL-ETA/BEDES-Manager#107]
There should be an error message that indicates the header is wrong.

**Comment by TravisWalterLBNL** [comment]
Depending on which wrong header I had, sometimes I got no message, other times I got this message:
Error in mapping: either BedesTerm and BedesAtomicTermMapping both exist or not. Term=(...)

**Comment by phgupta** [comment]
Fixed in 2f4c6ac0ae95f53cdda38df5ceebff998099ac9c

**Comment by TravisWalterLBNL** [comment]
Confirmed fixed.
