### ISSUE TITLE
confirm format of .csv header for application import

### ISSUE THREAD

**Issue by TravisWalterLBNL** [LBNL-ETA/BEDES-Manager#108]
Hadn't we decided on this? This is simple and readable (e.g., no newlines and no punctation).

"Application Term,Application Term Description,Application Term Unit,Application Term Data Type,BEDES Term,BEDES Term Description,BEDES Term Unit,BEDES Term Data Type,BEDES Atomic Term Mapping,BEDES Constrained List Mapping,BEDES Composite Term UUID,BEDES Atomic Term UUID,BEDES Constrained List Option UUID"

I don't think we need to describe the format of the columns in the column names because the rows themselves are examples of the format.

Also, the terminology we use isn't that clear, e.g.:
- "(list of {...})" isn't consistent with our convention elsewhere of units being in square brackets
- "BEDES Atomic Term = Value" doesn't make our format clear (e.g., we want constrained list = constrained list option for all except that last line, where we want atomic term = [value]). 
- Why mix terminology with "Application Term Enumeration" and "BEDES Constrained List Option"?

If we do keep this new header, we at least need to fix some things:
- Consistent separation of column names (some separated with just a comma, other with a comma and a space).
- "BEDES Constrained List Mapping..." is missing a right curly bracket.
- Change "Application Term Enumeration" to "Application Constrained List Option".

**Comment by phgupta** [comment]
This is fixed. The current sample file in the website has the updated headers.

**Comment by TravisWalterLBNL** [comment]
Confirmed fixed.
