### ISSUE TITLE
constrained list mappings not imported

### ISSUE THREAD

**Issue by TravisWalterLBNL** [LBNL-ETA/BEDES-Manager#111]
When I try to import a .csv with mappings of constrained list options (see attached), the application list options are imported correctly, but they are not mapped to the BEDES constrained list options (I just see "No Mapping" for every list option).

**Comment by phgupta** [comment]
I'm working on ensuring it works right after the import, but for testing purposes - refreshing the page should work.

**Comment by TravisWalterLBNL** [comment]
Confirmed fixed.

Seems to work, as long as there aren't too many list options. See issue #132.
