### ISSUE TITLE
import error message should be more informative

### ISSUE THREAD

**Issue by TravisWalterLBNL** [LBNL-ETA/BEDES-Manager#115]
When I try to import a composite term that is formed incorrectly (e.g., with "State = xyz123" in the term mapping for an application term called "abc"), I get an error messages saying "No data returned from the query.Term=(abc)", but it would be helpful if the message specified which application term and which constrained list this applied to. Something like 'Unrecognized list option "xyz123" of constrained list "State" for application term "abc"' would be better.

**Comment by TravisWalterLBNL** [comment]
Likewise if I try a bad constrained list (e.g., "Stat = CA" instead of "State = CA").

**Comment by phgupta** [comment]
Fixed in 8491c05f9e778934fef420b87a00d865508618f7

**Comment by TravisWalterLBNL** [comment]
I should get an informative message when I try to delete an application before deleting all of its application terms. I just get "An error occurred removing the application.".

**Comment by phgupta** [comment]
This is a duplicate of #96. We decided on it being low priority for now but this indeed seems important while testing.

**Comment by TravisWalterLBNL** [comment]
Error messages should say which application term caused the error. In the case of multiple errors, I think we can start with only the first error that is found being reported (rather than having to deal with listing potentially many errors).

I tried to import several application terms. One of the terms had an unofficial BEDES term unit, and the rest had official units. I received an error message saying "Error: Not an official BEDES unit.", but it didn't say which application term had the unofficial unit, and none of the terms were imported (not even the ones with official units). I had to try importing one term at a time to isolate which term had the bad unit. This is impractical when there are a lot of application terms.

**Comment by TravisWalterLBNL** [comment]
I am trying to import a single term, and all I get is an error message saying "Error creating terms". There should be some information about which colum is causing the error. I will attached the file I'm trying to import to an email since I can't attach .csv files here.

**Comment by TravisWalterLBNL** [comment]
Here's an error I encountered that should have a more descriptive error message: I imported som application terms, then added one term to the file, then tried to import the file again. All I got was "Error creating terms", but I should get something saying that I can't import an application term if I already have an application term with that name.

**Comment by phgupta** [comment]
Fixed "Error: Not an official BEDES unit." and the errors associated with the csv files in d91f4dd9fac7f334c721714b963b93a200ea654e

**Comment by TravisWalterLBNL** [comment]
Pranav said the mystery errors were caused by the application term name having too many characters (100), and that he will increase the limit.

**Comment by TravisWalterLBNL** [comment]
Confirmed fixed.
