### ISSUE TITLE
application import example file shouldn't have quotation marks

### ISSUE THREAD

**Issue by TravisWalterLBNL** [LBNL-ETA/BEDES-Manager#129]
For example, for the application term Advanced RTU Control Retrofits, in the atomic term mapping, it should just be Location = Roof, not Location = "Roof".

**Comment by phgupta** [comment]
I thought we decided to leave the quotation marks in the sample file but the underlying code would work for either implementation - quotation or no quotation.

**Comment by TravisWalterLBNL** [comment]
Why encourage people to do additional unnecessary work? This also avoids weird issues that I have seen before with quotation marks being stored differently on Windows vs. macOS and when copy/pasted from browsers vs. Microsoft vs. etc.

The underlying code should handle either, but the example shouldn't have extra quotes.

**Comment by phgupta** [comment]
Fixed in f421924742c13602b024344c52edfdef1a5e639c

**Comment by TravisWalterLBNL** [comment]
Confirmed fixed.
