### ISSUE TITLE
application import example has wrong data types and units

### ISSUE THREAD

**Issue by TravisWalterLBNL** [LBNL-ETA/BEDES-Manager#130]
1. For the "Year Built" application term: The correct data type is TimeStamp, not Timestamp.

2. Also for "Year Built": The correct unit is YYYY, not years. In general, if the data type is TimeStamp, the unit should be YYYY, YYYY-MM-DD, etc. If the unit is years, days, etc., the data type should be Integer (or maybe Decimal, I suppose).

3. For "Construction Status" and "Data Center - UPS System Redundancy": If there is a constrained list mapping (i.e., the "BEDES Constrained List Mapping" column isn't empty), the data type should be "Constrained List", not "String".

**Comment by phgupta** [comment]
1. The current table for data type has "Timestamp" not "TimeStamp". Do we want to change this to "TimeStamp" permanently?

I will fix the other two points.

**Comment by TravisWalterLBNL** [comment]
Yes, the correct value is "TimeStamp". For example, see "Data Type" here: https://bedes.lbl.gov/bedes-online/interval-end-date

**Comment by TravisWalterLBNL** [comment]
In the version you sent via email:

1. Quotation marks should be removed (see issue #129).

2. Timestamp should be TimeStamp.

3. For the "Advanced RTU Control Retrofits" application term, both the application and BEDES units should be "count".

4. For the "Year Built" application term, the BEDES unit should be "YYYY", not "years".

5. For the "Company" application term, I like that the application unit indicates that it is free text, but it could also indicate that the BEDES unit must come the official list. Also, instead of doing this in the "Company" application term, it would be better to do it for the last term, "Annual Savings ...". This is better because "Company" is a string and shouldn't have a unit, whereas "Annual Savings ..." should. We should set the "Annual Savings ..." unit to something like "British Thermal units (NOTE: application unit can be anything, but BEDES unit must come from the "Unit of Meaure" constrained list options)". It's likely that an application will use units that are similar to our official list, but aren't exactly the same.

6. If "Shared by Contact - Account ID" is meant to be an example of how an application term doesn't have to be mapped to a BEDES term, then maybe we should say that in the application term description.

**Comment by TravisWalterLBNL** [comment]
Also, two more things (that seem to be related) when I try to import the example file:

1. I get an error message saying there is different number of list options and list option UUIDs. It looks like it is caused by the "Data Center - ..." application term. It has 6 list options, but only 5 list option UUIDs. There is no UUID for the "Other" list option.

2. If I fix that by removing the last list option, I get an error message saying the constrained list mapping UUID is incorrect for the "Construction Status" application term. It looks like the final list option is "Other" but it uses the UUID for the list option "Occupancy".

It seems like a solution to both of these will require assigning UUIDs to the special extra options (i.e., "Other", "Unknown", "None", and "Not applicable"). The same option might need different UUIDs for each constrained list. Hopefully not, because that would be a lot of list options. Hopefully we can come up with a way to assign a UUID to each of the special extra options just once, and for that same UUID to be used no matter which list the list option is being used for.

One potential temporary solution would be to just not using any of the special extra options in the example file, so that we don't have to specify their UUIDs. But, that doesn't solve the problem of what to use for their UUID internally, or when exporting.

**Comment by phgupta** [comment]
1. Removed quotation marks in f421924742c13602b024344c52edfdef1a5e639c
2. Changed the units and descriptions for "Company", "Annual Savings..." and "Shared By Contact..." in 20c4105ea936fa1b23883aa7707e4e8aa66e87be

For the other two things, those errors popped up because the csv file needed to be updated by the new UUIDs. I agree that we should have one UUID for each of (Other, Unknown, None and Not Applicable) and all terms could map to these. However, creating a new UUID for each constrained list was a lot easier (no need to deal with creating a new table) so I have done that for now.

**Comment by robHitchcock** [comment]
Casey, the drupal master, is in the process of making scripted mods to the online dictionary to add these list options to all constrained list terms.  There will only be one instance of each list option with a single UUID.  Each list option will then reference all constrained list terms as a parent.

**Comment by TravisWalterLBNL** [comment]
Also, the app term "Annual Savings (2013-2017)\nTotal Primary Energy Savings" shouldn't have a newline. I know this is technically allowed, but I don't think we should encourage this by putting it in the example file.

**Comment by TravisWalterLBNL** [comment]
When I try to import the example file, I get an error message saying "Composite term already exists.", even though the list of composite terms is empty.

**Comment by TravisWalterLBNL** [comment]
On second thought, perhaps special characters shouldn't be allowed in application term names. Either that, or these characters should be converted during import. When I converted the "Annual Savings..." term, the newline character got dropped and the mapping manager showed "...2017)Total...".

**Comment by phgupta** [comment]
What should the special characters be converted to?

**Comment by TravisWalterLBNL** [comment]
Also, for consistency with the export filename (see issue #139), the file name should be "BEDES Application Import - Example.csv".

**Comment by TravisWalterLBNL** [comment]
In general, I have seen a lot of software that replaces weird characters with an underscore, but let's hold off on this until we have discussed as a team.

**Comment by TravisWalterLBNL** [comment]
Some more fixes are necessary:

1. For the "Company" application term, the term mapping has an extra trailing space that should be removed.

2. For "Construction Status", the name of the list option should be "Design development" (i.e., the second word should not be capitalized).

**Comment by TravisWalterLBNL** [comment]
Confirmed fixed.
