### ISSUE TITLE
application unit ignored on input

### ISSUE THREAD

**Issue by TravisWalterLBNL** [LBNL-ETA/BEDES-Manager#131]
When I import an application mapping, it looks like the application unit is completely ignored. When I click on the button to view the application term, there is a dropdown for unit, but it is blank no matter what I put for the application unit in the file I import. Instead of being a dropdown, this should be a free text field, and it should initially have the value I put in the import file.

**Comment by phgupta** [comment]
Duplicate of #128. Yes, I'm aware of this and I was going to work on all the UI elements at the end.

**Comment by phgupta** [comment]
Fixed in 08c268de63a3899b926ea507cea16acbcc928dc4

**Comment by TravisWalterLBNL** [comment]
Confirmed fixed.
