### ISSUE TITLE
not all constrained list mappings imported

### ISSUE THREAD

**Issue by TravisWalterLBNL** [LBNL-ETA/BEDES-Manager#132]
I tried to import a single application term that was a constrained list with, e.g., Alaska = AK, Arizona = AZ, etc. There were about 50 items in list, but only the first 30 or so were mapped correctly. The remaining just had New York = No Mapping, North Carolina = No Mapping, etc.

**Comment by phgupta** [comment]
Are the BEDES constrained list options supposed to be abbreviations - AK, AZ...etc? I have added the full names as the constrained list options.

**Comment by TravisWalterLBNL** [comment]
Yes, the list options should be the abbreviations: https://bedes.lbl.gov/bedes-online/state

**Comment by TravisWalterLBNL** [comment]
GitHub won't let me attach the .csv file I was importing, so I'll email it separately.

I attached a screenshot of the result (look near the bottom). Many of the list options were mapped, but many show "No Mapping". Clearly, all should have been mapped.

I noticed that at about halfway through the list (between New Mexico and New York), the order of list options in the .csv file no longer matched the order shown in the mapping manager. It was at this same point in the list that the mapping manager started showing "No Mapping" instead of the correct mapped value.

<img width="1440" alt="Screen Shot 2020-03-18 at 10 10 26 AM" src="https://user-images.githubusercontent.com/22945142/76987619-b709a300-6900-11ea-99ae-d27149b1db34.png">

**Comment by TravisWalterLBNL** [comment]
I just tried this again, and this time, intead of only some the list options being mapped correctly, none of them were.

**Comment by phgupta** [comment]
Fixedi in 93f67e5b11c896badc8fd0e6cf676397b9e7d1ae

**Comment by TravisWalterLBNL** [comment]
Confirmed fixed.
