### ISSUE TITLE
application terms export

### ISSUE THREAD

**Issue by TravisWalterLBNL** [LBNL-ETA/BEDES-Manager#139]
There are some problems with the .csv file that I get when I export my application terms:

1. There shouldn't be a newline before the header.

2. The header row should match the example import file.

3. The application and BEDES data types are missing.

4. In the term mapping column and the list mapping column, there should be spaces around the equals sign, e.g., "Construction Status = [value]" instead of "Construction Status=[value]".

5. In the two mapping columns, mappings should be separated by newlines, not by "|".

6. Quotation mark should be removed.

7. Overall, I think that if I import a .csv file into an application, and then I download it back to a .csv, the two .csv files should match. This is currently not the case.

8. Rather than just sample.csv, the filename should indicate the name of the application, e.g., "BEDES Application Export - <application name>.csv".

**Comment by phgupta** [comment]
Partially fixed in f650e9403f876676b2b2efea3e0dc048be6bfa61 and be9eb28da07394a614949f49e6e12d31170a6487. For now, everything but the "App Term Data Type" and "BEDES Term Data Type" column works.

**Comment by TravisWalterLBNL** [comment]
In the "BEDES Atomic Term UUID" column, the UUIDs are correctly separated by newlines, but there should not be a newline after the final UUID. Same thing for the constrained list option UUIDs.

**Comment by TravisWalterLBNL** [comment]
The output file name should be "BEDES Application Export - <application name>.csv", not just "sample.csv".

**Comment by TravisWalterLBNL** [comment]
When I import the example file, then export it, then compare the two, I am seeing some differences (aside from the data type columns):

1. Some of the values in the 'BEDES Term Description' column are different in the import and export files. It looks like this is because the export file is overwriting what was in the import file with what it found in the BEDES dictionary when the composite term is just one atomic term, but it's not clear if this is the case. If this is the case, then the example import file should be fixed (see issue #130) to use the same descriptions as the dictionary. If it's not the case, then something is wrong with export.

2. Some of the columns in the export file have trailing newlines that shouldn't be there:
BEDES Atomic Term Mapping
BEDES Constrained List Mapping
BEDES Atomic Term UUID
BEDES Constrained List Option UUID

**Comment by TravisWalterLBNL** [comment]
When I export an application that has application terms with commas in their names, I get a .csv file that can't be parsed. It looks like the problem is that fields containing commas are not wrapped in quotation marks.

For example, the file has this:
Computer Density (Number per 1,000 ft2),...

Instead, it should have this:
"Computer Density (Number per 1,000 ft2)",...

**Comment by TravisWalterLBNL** [comment]
I tried to export an application term whose name included the pound sign (#), and in the exported .csv file, everything after the pound sign (and including it) were dropped from the file. For example, my application term name was "Fuel Oil #1 Use (kBtu)", but the second line of my export file was just "Fuel Oil ", without any commas or any other fields or anything.

**Comment by phgupta** [comment]
Partially fixed in a5b883b073f1d39df16f059d5a44f41b19462231

1. BEDES Atomic Term UUID and BEDES Constrained List Option UUID have no trailing newlines.
2. Output filename has been changed to "BEDES Application Export - APP_NAME.csv".
3. Fixed issue with special characters in app term names (NOTE: I tested multiple special characters and all of them worked except '#'. Not sure how it is being treated by the csv file)

Note
1. I didn't find trailing newlines in any of the header columns.

**Comment by TravisWalterLBNL** [comment]
I'm still seeing newlines in the values (not the header) for the following columns:
BEDES Term Description
BEDES Constrained List Mapping
BEDES Constrained List Option UUID

**Comment by TravisWalterLBNL** [comment]
Also, for some terms, the 'BEDES Term Data Type' is non-blank in the import files, but is blank in the export file. I will email an example import file.

**Comment by TravisWalterLBNL** [comment]
The blank 'BEDES Term Data Type' in the export file (despite being non-blank in the import file) was due to composite terms created before the data type functionality was implemented. After deleting those composite terms, the import and export 'BEDES Term Data Type' now matches.

**Comment by TravisWalterLBNL** [comment]
The following columns still have trailing newlines in the data (not the header):
BEDES Term Description
BEDES Constrained List Mapping
BEDES Constrained List Option UUID

If these newlines are in the dictionary for the term descriptions, then that's OK, but if they're being added, they shouldn't be.

But, for the constrained list mapping and the constrained list option UUIDs, they should definitely not have trailing newlines.

**Comment by phgupta** [comment]
Fixed in 32b89e8f630d5680d3ee98790280a7ddfdaf3844

**Comment by TravisWalterLBNL** [comment]
Fixed (except for the descriptions, because the newlines are in the dictionary).
