### ISSUE TITLE
error when importing: missing required parameters

### ISSUE THREAD

**Issue by TravisWalterLBNL** [LBNL-ETA/BEDES-Manager#156]
When I try to import a .csv file that I think should be fine (see email), I get this error message: "Missing required parameters.. Term=(Energy Cost ($))".

**Comment by phgupta** [comment]
Fixed in 6b9058b0a7cd156bbd2a5c5a5a12737f9ca88414

**Comment by TravisWalterLBNL** [comment]
Confirmed fixed.
