### ISSUE TITLE
should be able to delete multiple composite terms

### ISSUE THREAD

**Issue by TravisWalterLBNL** [LBNL-ETA/BEDES-Manager#159]
In the list of composite terms, I have to delete one term at a time (and I have to confirm by clicking yes in the dialog box). I should be able to delete lots of terms at the same time (e.g., with a "select all" box that I can toggle).

**Comment by wizonesolutions** [comment]
@TravisWalterLBNL Do we have similar "select all" functionality elsewhere in the application? (Asking for estimation purposes.)

**Comment by TravisWalterLBNL** [comment]
No, I don't think there is any "select all" funcionality elsewhere.

**Comment by wizonesolutions** [comment]
Plan for this:

- attempt to add a column with a checkbox to the terms the user can delete
- when any of those checkboxes are selected, display a "Delete Selected Terms" button
- clicking the button prompts the user to confirm ("You are about to delete [NUMBER] composite terms. Are you sure?"), then deletes the selected terms

**Comment by wizonesolutions** [comment]
This is on staging now along with the other one I mentioned last week. I am aware that the "Delete Selected" button being all the way at the bottom isn't the best, but I didn't want to waste time fighting the layout and figured we could handle it separately. Functionally, everything is solid.

**Comment by wizonesolutions** [comment]
QA instructions:

- go to the composite terms page
- ensure you've created some terms
- select two or more
- click the Delete Selected button that appears at the bottom
- click Yes
- ensure only the selected terms are deleted

Also test that viewing and deleting individual terms still works as expected.

**Comment by TravisWalterLBNL** [comment]
Looks good to me.

The only thing I noticed was that the application term mappings don't seem to get updated when a composite term is deleted:
- create a new composite term
- create a new app term
- map the new app term to the new composite term
- delete the new composite term
- click on the app term in the list of terms for that app
- on the right side, the deleted composite term is still listed
- but, when i export the app to .csv, the app term appears to not be mapped (i.e., the deleted composite term is not in the .csv file)

**Comment by wizonesolutions** [comment]
Just to clarify: Did app terms get updated upon deleting composite terms previously? I am not deleting the terms any differently, so I suspect this doesn't happen if you delete individual terms either. Might be something we should open as a separate issue.

**Comment by TravisWalterLBNL** [comment]
I confirmed that this happens on production too: I delete the composite term, it still shows as being mapped to, but isn't in the exported .csv. So it seems like this is unrelated to this issue (#159). I moved this into a separate issue: #214.

So, that means the fix for this issue (#159) is ready to deploy to production.

**Comment by wizonesolutions** [comment]
This is on production now for final review.

**Comment by TravisWalterLBNL** [comment]
Fixed on production.
