### ISSUE TITLE
vulnerable dependencies

### ISSUE THREAD

**Issue by TravisWalterLBNL** [LBNL-ETA/BEDES-Manager#165]
I have been receiving emails from GitHub about security advisories related to vulnerable dependencies. The following dependencies should be checked:

lodash
minimist
kind-of
serialize-javascript
set-value
webpack-dev-server
js-yaml

**Comment by TravisWalterLBNL** [comment]
Another dependency to check:
dot-prop

**Comment by TravisWalterLBNL** [comment]
Also:
elliptic

**Comment by TravisWalterLBNL** [comment]
Also:
bcrypt

**Comment by TravisWalterLBNL** [comment]
Also:
node-forge

**Comment by TravisWalterLBNL** [comment]
Also:
webpack-subresource-integrity

**Comment by caseycobb** [comment]
Marking as done - accepted on our JIRA.
