### ISSUE TITLE
figure out workflow for approving mappings

### ISSUE THREAD

**Issue by TravisWalterLBNL** [LBNL-ETA/BEDES-Manager#169]
Probably a backend function that just switches the owner to BEDES and sharing to Approved for all composite terms in an application?

**Comment by TravisWalterLBNL** [comment]
See issue #92.

**Comment by TravisWalterLBNL** [comment]
Making an application BEDES approved will be something that happens manually on the backend by LBNL and will probably not happen very often (e.g., quarterly).

**Comment by TravisWalterLBNL** [comment]
When an application becomes BEDES approved, all of it's application terms and composite terms should become BEDES approved (which means the owner=BEDES and sharing=Approved).

**Comment by robHitchcock** [comment]
@wizonesolutions It appears Travis already started an issue on the BEDES approval process. But we need to think through that process a bit in order for you to implement any necessary changes.

**Comment by wizonesolutions** [comment]
Alright, let me know.

**Comment by wizonesolutions** [comment]
@TravisWalterLBNL Just checking in for any updates.

**Comment by TravisWalterLBNL** [comment]
No updates yet. We will discuss internally tomorrow and let you know.

**Comment by TravisWalterLBNL** [comment]
Closing this issue, which was meant for discussion of behavior. Instead, will open a separate issue with specific instructions.
