### ISSUE TITLE
Application Mapping import issues

### ISSUE THREAD

**Issue by robHitchcock** [LBNL-ETA/BEDES-Manager#170]
1. On successful import all imported terms are displayed with Sharing=unknown. Refreshing the page correctly displays Owner=*me* and Sharing=Private for all BEDES Composite Terms, but this should not take a refresh.
2. Application terms that are mapped to BEDES Atomic Terms currently display blank Owner and Sharing column fields. Appropriate display should be Owner=BEDES and Sharing=Approved for these terms.
3. Minor issue is that it is not clear that the Owner and Sharing properties relate to the Mapped BEDES Term Name (rather than the Application Term Name). It would be helpful if the column headers for Owner and Sharing indicated this fact (e.g., BEDES Term Owner and BEDES Term Sharing).

**Comment by TravisWalterLBNL** [comment]
Looks like part 1 is covered by issue #112.

**Comment by TravisWalterLBNL** [comment]
Part 2 is covered by issue #184.

**Comment by wizonesolutions** [comment]
This is on production now, and I think it wound up being done since I see that I updated the column names in applications.

**Comment by TravisWalterLBNL** [comment]
Part 3 is fixed on production. Parts 1 and 2 covered by other issues.
