### ISSUE TITLE
Making an Application Mapping Public

### ISSUE THREAD

**Issue by robHitchcock** [LBNL-ETA/BEDES-Manager#171]
An Application Mapping is made Public by going to the Applications tab (https://bedes-manager.lbl.gov/applications), clicking on the edit pencil icon to the left of the desired Application, selecting the Application Options tab in the upper left, choosing the Public option under the Sharing pull-down list, and clicking the Save button. There are a few issues with this process.

1. A small font note below the Sharing pull-down list incorrectly indicates that the user must contact BEDES Administrators to make the application public. This is not correct and this note should be removed.
2. Selecting Public and hitting Save does not appear to do anything unless you refresh this page. A refresh should not be necessary and perhaps a successful operation notice should be displayed.
3. After successfully making an application public, the Application Options tab (https://bedes-manager.lbl.gov/applications/77/edit) no longer appears for the public application. This means that there is no way to revisit the Application Name and Description text boxes. Nor can you revert an Application from Public back to Private if desired. I am not sure if editing Name, Description, and Sharing should be allowed after making an Application public, but a user should be able to still access the Application Options tab even if editing is disallowed.

**Comment by robHitchcock** [comment]
@wizonesolutions Kevin - I noticed that I created this more explicit issue related to making applications public. This details needed enhancements to the overall process.

**Comment by wizonesolutions** [comment]
Yes, these changes have already been implemented in development. I'm not sure what process @caseycobb wants to use for UAT, but at some point we will get sign-off from your end.

The current behavior of point 3, by the way, was to not allow modifying application options once public (except for Admins). So I left it that way and only removed the edit permission requirement that was hiding the Application Options tab.

**Comment by robHitchcock** [comment]
I have verified implementation of the dev site as described by Kevin.

**Comment by caseycobb** [comment]
Marking as done - accepted on our JIRA.
