### ISSUE TITLE
incorrect unit displayed for composite term

### ISSUE THREAD

**Issue by TravisWalterLBNL** [LBNL-ETA/BEDES-Manager#178]
I created a composite term (Gross Floor Area) by importing an application mapping and specifying its unit (ft2) in the import file. But when I view the composite term, its unit is incorrectly listed as YYYY-MM-DD. Strangely, when I export the application mapping to .csv, the export file has the correct unit (ft2).

**Comment by robHitchcock** [comment]
Also, Data Type is not displayed when viewing a composite term. Should this field be added to the display?

**Comment by TravisWalterLBNL** [comment]
@robHitchcock See issue #177.

**Comment by TravisWalterLBNL** [comment]
It seems like the unit is somehow sticking to what it was previously. For example, if I click on a date-related composite term right after I log in, the unit is correctly shown as YYYY-MM-DD, but if I then click on an area-related composite term, it incorrectly shows the unit as YYYY-MM-DD. If I log out and close the broswer tab, then open the site up in a new tab and log back in, but this time I first click the area term, it shows the unit correctly as ft2, and if I then click the date term, it incorrectly show the unit as ft2.

**Comment by wizonesolutions** [comment]
This is ready for review on stage.

**Comment by TravisWalterLBNL** [comment]
As with issue #185, this seems to be fixed for newly created composite terms, but not for previously imported composite terms. Strangely, when I click on a previously imported composite term after clicking on a newly created composite term, I now see all the details from the newly created term (BEDES Terms, Unit, UUID, etc.), rather than just the unit, even though the UUID in the URL does seem to reflect the previously created term.

**Comment by TravisWalterLBNL** [comment]
If it is too difficult to apply this fix retroactively, one option would be to just delete and re-import all our mappings. The downside is that if someone has already mapped an application term to one of those composite terms, then that mapping would be broken. Is there a way to check if any of those composite terms have been mapped to (e.g., by other user accounts with private mappings)? If not, then I'd say we should delete and re-import.

**Comment by wizonesolutions** [comment]
We're looking into this. Will let you know.

**Comment by wizonesolutions** [comment]
@TravisWalterLBNL Can you re-check this or link me to some examples of this not working for old terms? Here's what I did:

- I loaded the current production code without the fix
- I loaded NYSERDA, which created private composite terms as that user
- I confirmed the issue with the "sticky" unit display
- I switched to the code with the fix
- I logged in as the same user and ensured that the unit now updated.

The unit displayed correctly for the already-imported terms as well. I wonder if, when reviewing this, you mixed it up with another issue? This is only the one about the unit display.

There _is_ a separate issue with some of the imported terms (looks like they're from NYSERDA?) where they don't load properly, but ones that do load properly show the right units. (The ones near the bottom work alright.) I'm looking into the separate issue.

**Comment by TravisWalterLBNL** [comment]
Fixed on staging.
