### ISSUE TITLE
when searching for terms, composite terms have wrong data type

### ISSUE THREAD

**Issue by TravisWalterLBNL** [LBNL-ETA/BEDES-Manager#185]
On the "Search for Terms" page, in the search results, if the Term Type is Composite Term, the Data Type column currently says Composite Term, but instead it should say the data type of that composite term (e.g., Integer, Decimal, String), as it does with rows where Term Type is Atomic Term. The data type of a composite term is the data type of the rightmost atomic term in the composite term.

**Comment by wizonesolutions** [comment]
Ready for review on stage.

**Comment by TravisWalterLBNL** [comment]
Looks good for a composite term that I just created, but the terms that I had previously imported are still showing Data Type = Composite Term.

**Comment by TravisWalterLBNL** [comment]
Same comment as on issue #178: https://github.com/LBNL-ETA/BEDES-Manager/issues/178#issuecomment-897764363

**Comment by wizonesolutions** [comment]
@TravisWalterLBNL Please try to re-import/recreate some composite terms on staging and see if this and #178 are working now.

**Comment by TravisWalterLBNL** [comment]
@wizonesolutions I just looked at staging and I'm not seeing any of the BEDES atomic terms. It looks like you need to re-import the BEDES dictionary.

**Comment by wizonesolutions** [comment]
@TravisWalterLBNL Sorry about that. It's re-imported now.

**Comment by TravisWalterLBNL** [comment]
Fixed on staging.
