### ISSUE TITLE
there should be a way to search for application terms

### ISSUE THREAD

**Issue by TravisWalterLBNL** [LBNL-ETA/BEDES-Manager#186]
If I'm on the "Applications" page and I use the search bar, it is search the names of the applications. There should be a place where I can search for the names of application terms. Ideally, I would be able to use the same search bar to search for the names of application terms that are in different applications. An easier, but less ideal, solution would be to put a search bar at the top of the page that lists the application terms within a particular application, and that would perform a search on the application terms within that application.

**Comment by wizonesolutions** [comment]
Do you mean that you want to search for application terms within applications when on the application overview page?

The second option, a simple filter search for application terms in a given application is probably easier, but let's talk about the first option more.

Would the search results be a list of applications or a list of application terms? If application terms, seems like we would need a new screen, e.g. Search for Application Terms, rather than reusing the Applications screen?

**Comment by TravisWalterLBNL** [comment]
There is no need to search the names of applications. It is unlikely there will be so many applications that they can't be quickly browsed through or sorted alphabetically to find what someone is looking for. Instead, it would be useful to search for application terms within applications, without needing to know which application it is in.

So, we would probably need a new page for application terms (analgous to the pages for BEDES terms and composite terms). There would be a search bar at the top and the search results would be a list of application terms and the composite terms they are mapped to (and maybe other things, e.g., Owner, Sharing, Data Type). By default, we would show all application terms (as with the composite terms page), as opposed to the BEDES terms page (which shows no results by default).

**Comment by wizonesolutions** [comment]
@TravisWalterLBNL @robHitchcock One question I need your input on: When browsing to a search result, do we want to open the _application_ or the _application term_? In my mind, the application makes more sense so that they can see the application term in context (and since they are typically not going to edit it, as they wouldn't be searching for their own application).

Do you agree?

**Comment by wizonesolutions** [comment]
Here is a mockup of what I'm thinking:

[BDS-48.pdf](https://github.com/LBNL-ETA/BEDES-Manager/files/7662492/BDS-48.pdf)

An alternative idea I considered but decided was better to save for later was to split the Applications screen in two (or have a tab on it) and have the application terms there. But I felt that there wasn't enough space for both tables to be displayed comfortably, and that I would probably run into layout issues when trying to add a second grid. Better to avoid that and start with a separate page, I figure. A bit easier to deal with. Most of the work here is on the backend and not visible anyway.

**Comment by robHitchcock** [comment]
@wizonesolutions I am not sure what you mean by "When browsing to a search result". Your mockup looks ok to me. Do you mean when the user goes "deeper" by selecting the button to the left under Application Name? I'm not sure what that would do, or even if it is needed.

**Comment by wizonesolutions** [comment]
@robHitchcock Yes, that's what I mean. Let's back up, then: if someone's searching for an application term, what might they want to do when they find it? I thought that the pencil icon would view the application. If there are no actions they can take after searching, what is the purpose of the search? That's how I think about it.

**Comment by robHitchcock** [comment]
@wizonesolutions @TravisWalterLBNL I will let Travis chime in on this. I believe the intent of being able to search Application Terms is to see if an existing Application has already mapped an Application Term similar to one I am wanting to map, and if so, what Composite Term (or possibly Atomic Term) they used/created for their mapping. This is most likely part of the new process we have defined for performing Application mappings. So it may not need a new separate page at the topmost Manager level, but rather be displayed as a pop-up in our new process. The end goal is to see the Composite Term used in an Application mapping, so no need to drill down further than your mockup shows, but perhaps a need to select the Composite Term used in a mapping.

**Comment by TravisWalterLBNL** [comment]
The mockup looks good to me, except I would change the order of the columns to this: Application Term Name, Mapped BEDES Term Name, Application Name, Owner, Sharing.

If I click on one of the search results, I should see the same page I would see if I first clicked on an application, then clicked on an individual application term (i.e., the app term name, description, data type, unit, etc. on the left side, and, most importantly, the composite term it is mapped to on the right side). If the app is owned by someone else, things should be grayed out and I shouldn't be able to edit anything. I don't think I would care about the other application terms in the application.

The purpose of searching for an application term is to find out which composite term it is mapped to. For example: "My app term is X. Does anyone else have a similar app term? If so, what did they map it to? OK, I'll map mine to that too (or something similar).".

For now, there won't be any action I can take, per se, after I've found the application term. I'll just have to remember the composite term it was mapped to, then either go map my own app term to that composite term, or go and make a new composite term based on it.

The eventual plan is that there will be an action to take after I've found the application term. When we do the new UI redesign we discussed with Kevin, I should be able to just click on the composite term that the app term is mapped to and automatically have my app term mapped to that composite term.

**Comment by wizonesolutions** [comment]
Thanks @TravisWalterLBNL , that makes sense and answers my question as to what a typical visitor would want to do with the information.

**Comment by wizonesolutions** [comment]
@TravisWalterLBNL Just to update progress, this one will take longer than expected because more code was missing from the frontend than I anticipated. I thought I would be able to expand on the existing app term code, but it is built around the concept of having an active application or application term. This is solvable; it just takes more time.

I'm endeavouring to maintain the schedule I sent you as closely as possible. I'll take a look at it once I've worked on this more this week and see how feasible that is.

**Comment by wizonesolutions** [comment]
@TravisWalterLBNL App terms can be mapped to both atomic and composite terms, but only composite terms have owners. What do we show in the Owner column if the mapped term is atomic? "BEDES"?

**Comment by wizonesolutions** [comment]
Never mind; I believe you intended Owner and Sharing to represent the _application_ rather than the mapped term.

**Comment by TravisWalterLBNL** [comment]
Wherever we are on the site, if we are showing details for atomic terms, their owner should be "BEDES" and their sharing should be "Approved". For example, the "Search for Terms" page (on production) currently shows this correctly.

In the mockup from Dec. 6, the owner and sharing columns should correspond to the application term (which will have the same owner and sharing as the application itself).

**Comment by wizonesolutions** [comment]
Thanks. This ticket is on staging now. Have a look and let me know if anything looks wrong. Pay particular attention to scopes/ownership/permissions.

Right now, I have deliberately re-used the application edit screen, so clicking the application's Back button will take you back to the application screen. I figured it was not worth making a whole new screen just for this, and that we could do it in a follow-up if necessary. To get back to the list, go back in your browser or click Application Terms again (it saves its state).

**Comment by TravisWalterLBNL** [comment]
This looks great. Once it's deployed to production and tested there, I will close this issue.

Re-using the application edit screen is fine.

**Comment by wizonesolutions** [comment]
Deployed to production.

**Comment by TravisWalterLBNL** [comment]
Looks good on production.
