### ISSUE TITLE
should be able to modify or delete an application after making it public

### ISSUE THREAD

**Issue by TravisWalterLBNL** [LBNL-ETA/BEDES-Manager#207]
If I create an application and it is private, I can delete it or modify it. But, once I have made it public, I am no longer able to. Making it public should affect who else can see it, but it shouldn't affect what I can do to it. As long as I am the owner, I should be able to modify it. I should also be able to change it back from public to private.

**Comment by wizonesolutions** [comment]
Partial overlap with #192. I'll handle "able to modify application terms and options" in that one and "able to change from public back to private and delete" in this one. In practice, I'll likely tackle them together.

**Comment by TravisWalterLBNL** [comment]
Agreed. Significant overlap with issue #192. Let's keep both to make sure all aspects are handled.

**Comment by wizonesolutions** [comment]
This issue is on production now @TravisWalterLBNL @robHitchcock

**Comment by TravisWalterLBNL** [comment]
See new issue #213 for being unable to export public applications.

**Comment by TravisWalterLBNL** [comment]
For clarity, let's move all remaining conversation about this issue to #209 instead (since there is so much overlap).

**Comment by TravisWalterLBNL** [comment]
See #209.
