### ISSUE TITLE
Modifying Public Application Mappings

### ISSUE THREAD

**Issue by robHitchcock** [LBNL-ETA/BEDES-Manager#209]
The owner of an Application mapping should be able to modify it after making it Public.
Currently, after making an application Public the owner can no longer edit Application Options, add New Terms, or Import/Export Application Terms (CSV)
![image](https://user-images.githubusercontent.com/7998768/136596824-8402945b-5e2b-4301-9574-4b00d417a429.png)
![image](https://user-images.githubusercontent.com/7998768/136596877-3d48a345-05b5-44f9-acb1-47985e78bc83.png)
Overlaps with #207

**Comment by wizonesolutions** [comment]
@TravisWalterLBNL Thanks for the confirmation. cc @caseycobb

**Comment by wizonesolutions** [comment]
This is deploying to staging. Give it 10 minutes or so.

- Fixed the screen update issue and made public applications/app terms editable for users with permission.
- Also made some internal fixes to the data tables (listings). Let me know if any expected functionality there such as filtering is missing. Looked OK on my side, but I didn't check them all since they are made using the same pattern.

@TravisWalterLBNL @robHitchcock

**Comment by TravisWalterLBNL** [comment]
Looks good on staging.

**Comment by TravisWalterLBNL** [comment]
I'm testing all these overlapping issues (#192, #207, #209, and #213) on production. Let's put the remaining unresolved things from #192 and #207 here, and the things specific to exporting with #213.

Here's what works:
- I can't modify composite terms or applications that are public but owned by someone else.
- I can modify and delete public composite terms owned by me.
- I can delete an application term from a public application owned by me.
- I can modify the application options for a public application owned by me.

Here's what doesn't work:
- I can't make a new application term in a public application owned by me. If I click on "New Term", I am brought to the screen where I would normally enter the application term name, description, etc., but everything is grayed out.
- I can't unmap a composite term from an application term in a public application owned by me. It appears to be unmapped initially, but if I go to another application and view another application term, then come back to the application term I unmapped, it is shown as being mapped to the composite term in was initially mapped to.

**Comment by wizonesolutions** [comment]
Can you check this again on staging/production? I am seeing the correct behavior with a non-admin and admin user on an application they are the owner of. I can also unmap. Be sure to click Save after unmapping.

**Comment by TravisWalterLBNL** [comment]
I'm not sure what was happening before, but everything seems to be working on production now. Closing #209, #207, and #192, but leaving #213 open.
