### ISSUE TITLE
UX: Search Term Tab

### ISSUE THREAD

**Issue by jateeter** [LBNL-ETA/BEDES-Manager#25]
A return to the search term tab brings me back to my previous search result; which is fine, but it possibly should also place the thing I searched for in the search box as well.

<img width="1725" alt="Screen Shot 2019-03-08 at 1 41 56 PM" src="https://user-images.githubusercontent.com/934513/54054730-30c46800-41a8-11e9-9a41-fc8c0bc445df.png">

**Comment by TravisWalterLBNL** [comment]
Could not reproduce. Seems like it was fixed somehow.
