### ISSUE TITLE
Verify Git Repo "README.md" is correct

### ISSUE THREAD

**Issue by jateeter** [LBNL-ETA/BEDES-Manager#48]
Need to verify that the instructions contained in the README.md are valid. I've not tried this since AWS became available and the last time (on Mel's machine) had problems.

**Comment by phgupta** [comment]
Update instructions (code and db table structures have changed)

**Comment by caseycobb** [comment]
@TravisWalterLBNL this is confirmed. Kevin was able to get his local set up from the README.
