### ISSUE TITLE
Mapping constrained list options

### ISSUE THREAD

**Issue by robHitchcock** [LBNL-ETA/BEDES-Manager#73]
Problems with user interface when trying to create new application term enumerations and map them to BEDES constrained list options.
Changing application term Type of Term from Value to Constrained List does not reliably cause List Options controls to appear. Manually refreshing page seems to help.
Adding New List Options beyond the point where you have to use the short scroll bar to the lower right of List Options causes the list of options to disappear.

**Comment by mspears-lbl** [comment]
Having trouble reproducing the constrained list mapping issue on my machine.  Can you indicate how the error occurs?

Which application term causes the error?
At which point do you try and change the Term Type from [value] to Constrained List?
Which BEDES Term are you mapping to? is it a composite term?

**Comment by robHitchcock** [comment]
I just tried a new application term mapping as follows:
1. Went to my existing application mapping "CPUC MF Attributes BayREN"
2. Added a new application term "Data Center Redundancy", mapped it to existing composite term "Data center UPS Equipment Redundancy", saved it with its type of term set to "Value", and returned to term list.
3. Went back to edit "Data Center Redundancy", changed its type of term to "Constrained List" and when the "New List Option" button appeared added a new application list option "N", mapped it to BEDES constrained list option "N" under atomic term "Equipment Redundancy", saved it and returned to term list.
4. Went back to edit "Data Center Redundancy" and although it still had a type of term of "Constrained List", the "New List Option" button did not appear, nor did my added list option "N".
5. Hit browser refresh button which returned me to application term list.
6. Now when I went to edit "Data Center Redundancy", the "New List Option" button was present along with my earlier added constrained list option "N" and its mapping.
7. Added another "New List Option" of "N+1" and saved without mapping this new list option, and returned to term list.
8. Went back to edit "Data Center Redundancy" and although the "New List Option" button appeared, there were no list options displayed.
9. Refreshed, which sent me back to term list, and when I returned to edit "Data Center Redundancy", everything appeared as it should.

So my takeaway is that it takes a manual refresh to display this page and all of its controls properly.  The input data and mappings appear to be getting saved OK, but not displayed properly without this manual refresh.

**Comment by robHitchcock** [comment]
A related problem is that now that my mapped constrained list option list goes below the bottom edge of my screen, a smaller vertical scroll bar appears to the right of this list.  However, when I try to click on this scroll bar, all of the list option controls disappear.

**Comment by robHitchcock** [comment]
These problems do not occur on a Mac using Chrome, but do occur on a PC Win10 using Chrome.
