### ISSUE TITLE
Application Term DataType

### ISSUE THREAD

**Issue by robHitchcock** [LBNL-ETA/BEDES-Manager#74]
Instead of the textbox labeled "Type of Term" on the Application Mapping page (see attached image), the textbox should be labeled "Data Type" and the contents should be the DataType of the Application/BEDES term (e.g., Decimal, Integer)
[Application Term DataType Issue.docx](https://github.com/LBNL-ETA/BEDES-Manager/files/3933824/Application.Term.DataType.Issue.docx)

**Comment by phgupta** [comment]
Both app_term and bedes_composite_term tables need to have a "data_type_id" column.

**Comment by TravisWalterLBNL** [comment]
Confirmed fixed.
