### ISSUE TITLE
Application mapping import not working

### ISSUE THREAD

**Issue by robHitchcock** [LBNL-ETA/BEDES-Manager#75]
I tried to import the "Example Format for Mapping Export" CSV file (attached file is the XLSX format since you cannot attach a CSV format here
[Import Test 1.xlsx](https://github.com/LBNL-ETA/BEDES-Manager/files/4093681/Import.Test.1.xlsx)
).
The import failed with no error report.
Also, the instructions, which only appear after you click the "Import Application Terms" appear to be left over from earlier versions, and only address the import of application terms, not completed mappings as expected. The available example "Download Sample File" also appears to be the prior version.

I do not see another import option that includes completed mappings.

**Comment by jateeter** [comment]
thx - made a new account.

Have you done anything with Transportation systems yet?

jt

**Comment by robHitchcock** [comment]
Specific outstanding import issues documented in new issues.  So closing this one.
