### ISSUE TITLE
Public application

### ISSUE THREAD

**Issue by phgupta** [LBNL-ETA/BEDES-Manager#92]
When an application becomes public, all the mapping's composite terms become public as well.

**Comment by TravisWalterLBNL** [comment]
Similarly, when an application becomes BEDES approved, all it's composite terms should become BEDES approved.

**Comment by TravisWalterLBNL** [comment]
To clarify: Making an application public will happen within the mapping manager by the owner of the application. Making an application BEDES approved will be something that happens manually on the backend by LBNL and will probably not happen very often (e.g., quarterly).

**Comment by wizonesolutions** [comment]
@robHitchcock Looks like this is already implemented. I went in, created a composite term, mapped it to an application term, and then made the application public. The composite term then also appeared as public. (Checked a little more; this is done on the backend.)

Regarding the BEDES-approved part, there's no Approved scope for applications right now. Do you want to open a separate issue for that?

**Comment by wizonesolutions** [comment]
One thing I can do in the context of this ticket is fix the issue where the application's composite term list is not immediately refreshed. They still show Private until the whole app is refreshed.

**Comment by robHitchcock** [comment]
Thanks. Yes, I believe the private to public process is already implemented correctly. I will start a new issue regarding BEDES approval.
Fixing the issue of not having to manually refresh to see changes would be helpful.

**Comment by TravisWalterLBNL** [comment]
So, this issue can be closed, right? Issue #112 covers the manual refresh topic, and issue #169 covers the BEDES approval topic.

**Comment by caseycobb** [comment]
@TravisWalterLBNL closing this issue as it has been demoed to and accepted by Rob. Should be on the live Heroku site now.
