### ISSUE TITLE
Add more BEDES Constrained List Options

### ISSUE THREAD

**Issue by phgupta** [LBNL-ETA/BEDES-Manager#97]
“Other, Unknown, None, Not applicable” are the four BEDES Constrained List Options that need to be added. Current implementation includes only "other".

**Comment by TravisWalterLBNL** [comment]
This issue refers to verifying the correctness of composite terms upon import.

But also, these special list options should be added to every constrained list (on the backend, but not necessarily on the website database).

**Comment by phgupta** [comment]
6e9e36e314eda30817f067416696844ade0aeb7a fixes it.

**Comment by phgupta** [comment]
6e9e36e314eda30817f067416696844ade0aeb7a fixes it.
